api/domain/sensor.py
updates to sensor.py to handle dswe and lst availability
=> cgaustin's mods to sensor.py for dswe and lst

api-dev-uwsgi.ini, api/domain/config.py, api/domain/sensor.py, api/lta.py, api/providers/ordering/__init__.py, api/providers/ordering/ordering_provider.py, api/transport.py, api/user.py, api/utils.py, requirements.txt, runserver, test/test_apiv0.py, test/test_flask_transportv0.py, transport.py
@dhill-usgs @klsmith-usgs please take a look when you have time
=> user authentication and tests

api/api_logging.py, api/lta.py, api/ordering/version0.py, api/providers/ordering/ordering_provider.py, api/user.py, requirements.txt, test/test_apiv0.py
@davidvhill @klsmith-usgs   here's my proposal for tracking and managing exceptions in the api.
heres my thought process:
- exceptions with the transport layer should only be related to server and transport activities. these will be captured in the log setup by the uwsgi server running the transport(flask) app. this is why I didn't include any try/except blocks in transport.py
- the api should always return an object that can be converted to JSON, even when theres an issue further down the stack. when there's a problem now the response is a dict of {"msg": "sorry theres been a problem, admins have been notified"}.  exception details are written to a log.
- we'll need to construct a listener for the error log, so that we're notified when errors are reported.
I think the logging objects …
=> api exception handling proposal

api/domain/order.py, api/domain/scene.py, api/domain/sensor.py, api/lpdaac.py, api/lta.py, api/ordering/version0.py, api/providers/inventory/inventory_provider.py, api/providers/ordering/ordering_provider.py, api/providers/ordering/production_provider.py, api/providers/validation/__init__.py, api/user.py, http_restful.py, test/test_apiv0.py, test/test_flask_transportv0.py, test/version0_testorders.py
=> Version0 development klsmith

api/__init__.py
Easier than what I was thinking it was going to entail.
=> Validation: removed <obj> from the error

api/domain/user.py, api/util/dbconnect.py
update the find_or_create_user method in user.py to a postgres upsert statement.
small change was needed to the execute method in dbconnect to return the value
from the upsert query coming in from user.py
=> update user details upon LTA authentication

api/transports/http.py, api/transports/http_production.py, api/transports/http_user.py
Production white list. Changes need to be made to config files.
=> Version0 development whitelist

api/util/__init__.py
=> lsrd-409  skip lowercasing note field on order submission

api/domain/restricted.yaml, api/providers/validation/validictory.py, test/test_apiv0.py, test/version0_testorders.py
=> lsrd-408  validation tests for stats requirements

api/domain/scene.py, api/interfaces/admin/version1.py, api/providers/administration/administration_provider.py, api/providers/production/production_provider.py, api/transports/http.py, api/transports/http_admin.py
enable admin scene status resetting to submitted or unavailable
=> Error resetting

api/domain/order.py, test/test_production_api.py
=> fix for resampling_method in the ordering conversion process

README.md
Added a table to summarize all available user operations, for an overview and to avoid scrolling
=> Add summary table user API ops

api/domain/sensor.py, api/external/lta.py, api/providers/ordering/ordering_provider.py, api/providers/production/production_provider.py, api/util/__init__.py, test/test_external.py, test/version0_testorders.py
Tomorrow's release of LEDAPS 3.0.0 & LaSRC 0.10.0 collection processing will be TURNED ON
=> Collections date restrictions

README.md, api/domain/__init__.py
* Update docs to describe available list-orders-ext endpoint
* Add list-orders-ext to VersionInfo (methods returned from api/v0, api/v1)
=> LSRD 663 - list orders

api/external/mocks/lta.py, test/test_external.py, test/test_flask_transport.py
Adds tests for all relevant major sub-modules which handle responses from LTA:
* **EE**: Get available orders, update orders status
* **Inventory**: verify_scenes, order_scenes, get_order_status, get_download_urls
=> LSRD 192 - lta unit tests

api/external/lpdaac.py, api/external/lta.py, api/providers/production/production_provider.py, api/system/errors.py, api/util/__init__.py, api/util/connections.py, test/test_production_api.py
[JIRA](https://my.usgs.gov/jira/browse/LSRD-797)
* Adds 403 to valid list of HTTP auto-retry errors
* Adds URL verification on responses coming from DAAC/LTA
* Adds ancillary external check for certain products
* Landsat LST requires a DAAC check (for ASTER)
* Blocks status-flow when external services are down
* Clean up some LTA XML interactions
=> LSRD 797 - http connection errors

api/domain/scene.py, setup/db_schema.sql, setup/espadev_espa_unit_test_schema.sql, test/test_production_api.py
* Adds a "status_modified" column to the ordering_scene table
* SQL Trigger function to update the column whenever "status" is updated
* Update Scene.py for the new attribute
=> LSRD 647 - add timestamps for status changes to scenes

CHANGELOG.md, README.md, api/__init__.py, api/domain/__init__.py, api/domain/mocks/order.py, api/domain/restricted.yaml, api/domain/scene.py, api/external/mocks/lta.py, api/external/mocks/onlinecache.py, api/external/onlinecache.py, api/interfaces/ordering/version0.py, api/interfaces/ordering/version1.py, api/notification/emails.py, api/providers/ordering/__init__.py, api/providers/ordering/ordering_provider.py, api/providers/production/production_provider.py, api/providers/validation/validictory.py, api/transports/http.py, api/transports/http_json.py, api/transports/http_user.py, docs/API-RESOURCES-LIST.md, examples/api_demo.ipynb, examples/api_demo.py, test/test_api.py, test/test_flask_transport.py, test/test_production_api.py, test/version0_testorders.py, unittest.cfg
**Ready for internal system test tomorrow May 24**
* **STAFF ONLY** Ability to cancel orders (new `cancelled` scene/order state)
* Put all errors/warnings in "messages" JSON field
* All error messages are "human readable" variation
* Uses "warnings" when ERS connection cannot be established
* Remove CFMask product (replaced by pixel_qa **STAFF ONLY**)
* Bug fixes for API responses (HTTP Codes, Messages)
* Ensures methods have status code representing the requested action 
* Add JSON filters to available-products, orders, and item-status
* Remove `POST` http method from available-products, replaced by `GET` JSON body
* Strip leading/trailing whitespace from Email Addresses
* Adds checks to onlinecache that a remote folder exists, for potential directory purge problems
1. The Public REST …
=> Release Candidate 2017.05

CHANGELOG.md, Makefile, api/notification/emails.py, api/system/logger.py, run/api-dev-uwsgi.ini, run/api-ops-uwsgi.ini, run/api-tst-uwsgi.ini, setup/Dockerfile, setup/docker-compose.yml
Special email for when all products in order are unavailable for processing. Includes the resolution note next to each scene name.
=> Release Candidate 2017.09

api/providers/inventory/inventory_provider.py, api/providers/production/production_provider.py, api/transports/http_user.py
Mitigate some issues with users getting 500 errors during ERS authentication
=> FIX: error handling in user auth

api/providers/production/production_provider.py
- make sure the scene gets updated with
the note from gen_ee_scene_list
- addresses a minor issue where orders
from ee that have missing aux data
had a blank note
addresses LSRD-2797
=> add a descriptive note for unavailable ee orders

api/external/lpdaac.py, api/providers/inventory/inventory_provider.py
- check lp daac resource first, then try dmid
- increase timeout for checking if lpdaac is available
- increase timeout for checking if a granule is available
=> updates to better handle checking LPDAAC products
