api/domain/mock_order.py
api/domain/scene.py
api/utils.py
test/test_production_apiv0.py

This is what I've initially come up with as a solution for testing some of the SQL heavy production api methods. I'm not sure how else to sufficiently test those methods without hitting a database.
the setUp method in test_production_apiv0 sets an environment var, thats picked up by api_cfg, and looks for a .cfgnfo-test file in order to connect to  a test DB instance. The MockOrder class is then responsible for adding and removing test instances from the db.
@davidvhill @klsmith-usgs

Version0 development cgaustin

---

api/providers/production/production_provider.py

we encountered a scenario where EE indicated many more scenes for an EE originated order than we had in the ESPA database.
This appears to have been caused by that EE order only having some of the scenes it contained at the time we loaded it into our system.
this mod will add any new scenes to the order.

if an order doesn't appear to have all the scenes from an EE order, try adding them again

---

api/domain/sensor.py
api/providers/production/production_provider.py

Orders coming in via EE don't pass through our typical order validation process. Which means we were trying to process scenes to SR based products, for days where we didn't have the required auxiliary data.
This catches that. @klsmith-usgs

Check incoming EE scenes for auxiliary data availability

---

README.md

I'm learning how to use this new tool and was pretty confused when I hit a validation error when sending the exact order that's listed in the readme example!
```
{'message': {'1 validation errors:': ["Value u'lc8027029201533lgn00' for field "
"'olitirs8.inputs[0]' does not match "
'regular expression '
"'^lc8\\d{3}\\d{3}\\d{4}\\d{3}\\w{3}.{2}$'"]},
'status': 400}
```
And indeed, it's right, after the 2015 year tag, there should be 3 digits for the day of the year. I tried 033, 133, and finally a 233 in that position worked, and my order submitted successfully.

Fixed invalid Landsat tile identifier

---

api/providers/production/production_provider.py

Due to issues with scenes from EE which cannot be reproduced locally, this adds some new logging outputs, both for every single scene, as well as those which **should** be marked `unavailable`. 
For every single scene, a new line: 
```
2016-12-27 17:35:02,787 [INFO]: check ee processing: {'status': 'submitted', 'name': 'LE71940222016150NSG00', 'order_id': 717, 'note': '', 'sensor_type': 'landsat', 'ee_unit_id': 1} in ./api/providers/production/production_provider.py:665
```
When a scene is unavailable, a new line in the info.log file will include:
```
2016-12-27 17:35:02,787 [INFO]: check ee unavailable: {'sensor_code': 'LE7', 'product_id': 'LE71930232016159NSG00', 'julian': '2016159', 'station': 'NSG', 'doy': '159', 'version': '00', 'year': '2016', 'path': '193', 'shortname': 'etm7', …
```

include scene info/status for every ee order

---

README.md
api/domain/__init__.py
api/interfaces/ordering/version1.py
api/transports/http.py
api/transports/http_user.py
test/test_flask_transport.py

* Adds "v" to response from `api/` 
* `{"v0": "Version 0 of the ESPA API", "v1": "Version 1 of the ESPA API"}`
* Handles GET `api/v0/available-products` more gracefully
* Updates `api/v0/` with 
* list-orders as the correct endpoint for getting users orders
* removed `/api/v0/request/<ordernum>`

LSRD 712 - Clean endpoints

---

api/providers/production/production_provider.py

* Fixes bug where all plots were submitted to "oncache" if any order in queue was ready for plotting
* Assumes only 1 plot per order, adds error handling if more are ever found

Hotfix only plot finished orders

---

api/providers/production/production_provider.py

* Will only log to debug handler if connectivity issues happen consecutively within 10min period
* Ceases notifications for intermittent connectivity issues

Use memcache to save connection status

---

api/providers/validation/validictory.py
test/test_api.py
test/test_production_api.py

* Allows `'response-readable'` in JSON request (primarily for espa-web)
* Outputs different validation messages if flag is present, otherwise behavior is unchanged

LSRD 732 - Add human readable output

---

api/domain/restricted.yaml
api/providers/validation/validictory.py

User just placed an order for CFMASK-only from a tm5_collection product, and was allowed to order plotting (not supported for plotting)

Add collections to restricted plot/stats

---

api/domain/order.py
api/providers/validation/validictory.py
test/test_production_api.py

Allows new orders coming through the ODI web site to move into production (ignore the response-readable flag)

Hotfix - Unrecognized key 'response-readable'

---

api/util/__init__.py

For a date like `LC08_L1TP_040033_20160224_20170224_01_T1`, this needs to convert to "2016055" julian doy. 
```python
>>> from api.util import julian_from_date
>>> julian_from_date('2016', '02', '24')
'055'
```

julian date must always be 3 characters

---

api/notification/emails.py

Allows `validate_email` regex to match `".pizza"` or other longer-than-normal domain extensions (e.g. normal being `".com", ".org", ".gov"`, etc.)

HOTFIX: Allow email domain ext longer than 4char

---

CHANGELOG.md
api/__init__.py
api/domain/restricted.yaml
api/domain/user.py
api/external/lta.py
api/external/mocks/lta.py
api/interfaces/ordering/version1.py
api/interfaces/production/version1.py
api/notification/emails.py
api/providers/inventory/inventory_provider.py
api/providers/ordering/ordering_provider.py
api/providers/production/__init__.py
api/providers/production/mocks/production_provider.py
api/providers/production/production_provider.py
api/providers/validation/validictory.py
api/system/logger.py
api/transports/http_production.py
api/transports/http_user.py
docs/API-RESOURCES-LIST.md
examples/api_demo.ipynb
examples/api_demo.py
test/test_api.py
test/test_production_api.py

**Ready for internal system test June 22**
* Enable cancel orders (now includes "queued" scenes)
* Ordering Pixel_QA stand-alone product
* Change inventory misses to note "No longer found in archive"
* User-specific order disposition
* ~~Restrict UTM Zone to match (+/- 3 zone) requested image-extents~~
* Raise InventoryConnectionException to produce warning messages
* Bug fixes: 
* list-orders: invalid username lookup
* User class: update last_login upon lookup 
* HTTP Methods: raise BadMethodResponse on url contains args
* item-status: raise error on lists supplied as filters
* logging: Debug/Info logic brought to api.system.logger
1. Public REST API: Allows `PUT` method against `order` resource, to supply `"status": "cancelled"`. Opens `pixel_qa` to public. 
1. Production API: Allows …

Release Candidate 2017.06

---

CHANGELOG.md
api/interfaces/production/version1.py
api/providers/production/production_provider.py
api/transports/http.py
api/transports/http_production.py
test/test_production_api.py

Production-API endpoint for resetting all "queued/processing" status. Allows for hard-stops of the processing cluster, or debugging hadoop job ingestion/completion issues.

LSRD-960: endpoint to re-set the database states

---

CHANGELOG.md
api/external/hadoop.py
api/external/mocks/hadoop.py
api/providers/ordering/ordering_provider.py
test/test_external.py

**READY FOR SYSTEM TEST**
Updates required for hadoop-2.8.0 migration
branch | PR
------ | ------
rb-2.21.0 | [espa-processing#351](https://github.com/USGS-EROS/espa-processing/pull/351)
* api.external.hadoop: 
* Update location of hadoop configs (for whitelisting worker nodes)
* Update deprecated `hadoop` commandline utilities to `yarn`, for handling orphaned jobs/scenes
* ordering_provider: Bugfix to allow cancelling scenes in a retry-state

Release Candidate 2017.07

---

CHANGELOG.md
api/domain/order.py
api/domain/products.yaml
api/domain/restricted.yaml
api/domain/sensor.py
api/providers/configuration/configuration_provider.py
api/providers/inventory/inventory_provider.py
api/providers/production/production_provider.py
api/providers/validation/validictory.py
docs/API-REQUIREMENTS.md
docs/AVAILABLE-PRODUCTS.md
docs/TERMS.md
setup/espadev_espa_unit_test_configuration.sql
test/test_api.py
test/test_production_api.py

Updates to use surface-temperature terminology, validation for UTM zone and pixel-resize units, auto checks for stuck jobs. 
branch | PR
------ | ------
rb-2.25.0 | [espa-processing](https://github.com/USGS-EROS/espa-processing/pull/356)
Envvar `ESPA_M2M_MODE` replaced with update to ordering_configuration table
* Changes to Landsat "ST" terminology (staff only)
* Image extents (below 80N/S) must match +/-3 UTM zones
* Pixel Resize must match output projection
* Auto-resubmit long-running hadoop jobs
* Cleanup M2M configurations for switching sources

Release Candidate 2017.11 

---

api/providers/validation/validictory.py

The hemisphere check for subsetting UTM scenes is not necessary. Please review the changes

Removing UTM hemisphere check

---

api/providers/production/production_provider.py

I didn't see anywhere else in the production_provider code where orphaned scenes are being identified and resubmitted.  Unless I missed something, this should be the only change needed.

added additional fields to update when calling Scene.bulk_update

---

api/domain/restricted.yaml
api/providers/validation/validictory.py
test/test_api.py
test/version0_testorders.py

- do not allow orders for modis/viirs ndvi if
the order contains modis/viirs products
other than the daily 500-m SR
- added additional testing to verify ndvi ordering
restrictions
- updated restricted.yaml to assist with ndvi
order validation

update handling of ndvi orders

---

api/domain/restricted.yaml
api/providers/validation/validictory.py
test/test_api.py

- handle Landsat and Modis/Viirs customization separately
- consider hdf-eos2 non-customized format for Modis/Viirs
- consider geotiff non-customized format for Landsat
- don't restrict Viirs NDVI ordering since VNP09GA is the only
available VIIRS product in ESPA
- update tests to handle new sensor-specific formats

updates for order restrictions

---

Makefile
api/domain/restricted.yaml
api/providers/ordering/ordering_provider.py

This updates the API to make ordering MODIS/VIIRS daily NDVI publicly available (also VIIRS daily SR product)

remove staff role for modis/viirs daily ndvi
